services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph_data:/dgraph
    ports:
      - "5080:5080"
      - "6080:6080"
    command: dgraph zero --my=zero:5080

  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph_data:/dgraph
    ports:
      - "8080:8080"
      - "9080:9080"
    depends_on:
      - zero
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --bindall --security="whitelist=0.0.0.0/0"

  ratel:
    image: dgraph/ratel:latest
    ports:
      - "8000:8000"
    depends_on:
      - alpha
    command: dgraph-ratel

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8008" # Assuming our MCP server runs on 8008
    volumes:
      - ./src:/app/src
    depends_on:
      - alpha
    environment:
      - DGRAPH_ALPHA_HOST=alpha
      - DGRAPH_ALPHA_PORT=9080

volumes:
  dgraph_data:
